package com.itcm.structural_design.database;

import static com.itcm.structural_design.activities.BasicActivity.currentUserEmailGlobal;

public class SQLHelper {

    public String updateSetWhereSQL(String table, String setColIndex, String setValue, String compareColIndex, String compareValue) {
        return String.format("UPDATE %s SET %s='%s' WHERE %s='%s'", table, setColIndex, setValue, compareColIndex, compareValue);
    }

    public String updateBT_SQL(double id_1_value, double id_2_value, double id_3_value, double id_1001_value, double id_1002_value, double id_4_value, double id_5_value, double id_6_value, double id_10_value, double id_25_value, double id_26_value, double id_27_value, double id_28_value, double id_39_value, double id_40_value, double id_56_value, double id_57_value, double id_58_value, double id_63_value, double id_70_value, double id_87_value, double id_88_value, double id_91_value, double id_92_value, String savedVersionTitle, int moduleActiveId, int categoryActiveId, int subCategoryActiveId) {
        return String.format("UPDATE %s SET %s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_VAL_ID_1, id_1_value,
                DBModel.COLUMN_VAL_ID_2, id_2_value,
                DBModel.COLUMN_VAL_ID_3, id_3_value,
                DBModel.COLUMN_VAL_ID_1001, id_1001_value,
                DBModel.COLUMN_VAL_ID_1002, id_1002_value,
                DBModel.COLUMN_VAL_ID_4, id_4_value,
                DBModel.COLUMN_VAL_ID_5, id_5_value,
                DBModel.COLUMN_VAL_ID_6, id_6_value,
                DBModel.COLUMN_VAL_ID_10, id_10_value,
                DBModel.COLUMN_VAL_ID_25, id_25_value,
                DBModel.COLUMN_VAL_ID_26, id_26_value,
                DBModel.COLUMN_VAL_ID_27, id_27_value,
                DBModel.COLUMN_VAL_ID_28, id_28_value,
                DBModel.COLUMN_VAL_ID_39, id_39_value,
                DBModel.COLUMN_VAL_ID_40, id_40_value,
                DBModel.COLUMN_VAL_ID_56, id_56_value,
                DBModel.COLUMN_VAL_ID_57, id_57_value,
                DBModel.COLUMN_VAL_ID_58, id_58_value,
                DBModel.COLUMN_VAL_ID_63, id_63_value,
                DBModel.COLUMN_VAL_ID_70, id_70_value,
                DBModel.COLUMN_VAL_ID_87, id_87_value,
                DBModel.COLUMN_VAL_ID_88, id_88_value,
                DBModel.COLUMN_VAL_ID_91, id_91_value,
                DBModel.COLUMN_VAL_ID_92, id_92_value,
                DBModel.COLUMN_TITLE, savedVersionTitle,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal
        );
    }

    public String updateBTThird_SQL(int id_1000_position, double id_1_value, double id_2_value, double id_3_value, double id_4_value, double id_5_value, double id_6_value, double id_10_value, double id_2026_value, double id_2027_value, double id_2034_value, double id_2035_value, double id_2042_value, double id_2043_value, double id_2048_value, double id_2049_value, double id_39_value, double id_40_value, String savedVersionTitle, int moduleActiveId, int categoryActiveId, int subCategoryActiveId) {
        return String.format("UPDATE %s SET %s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_ID_1000_POSITION, id_1000_position,
                DBModel.COLUMN_VAL_ID_1, id_1_value,
                DBModel.COLUMN_VAL_ID_2, id_2_value,
                DBModel.COLUMN_VAL_ID_3, id_3_value,
                DBModel.COLUMN_VAL_ID_4, id_4_value,
                DBModel.COLUMN_VAL_ID_5, id_5_value,
                DBModel.COLUMN_VAL_ID_6, id_6_value,
                DBModel.COLUMN_VAL_ID_10, id_10_value,
                DBModel.COLUMN_VAL_ID_2026, id_2026_value,
                DBModel.COLUMN_VAL_ID_2027, id_2027_value,
                DBModel.COLUMN_VAL_ID_2034, id_2034_value,
                DBModel.COLUMN_VAL_ID_2035, id_2035_value,
                DBModel.COLUMN_VAL_ID_2042, id_2042_value,
                DBModel.COLUMN_VAL_ID_2043, id_2043_value,
                DBModel.COLUMN_VAL_ID_2048, id_2048_value,
                DBModel.COLUMN_VAL_ID_2049, id_2049_value,
                DBModel.COLUMN_VAL_ID_39, id_39_value,
                DBModel.COLUMN_VAL_ID_40, id_40_value,
                DBModel.COLUMN_TITLE, savedVersionTitle,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal
        );
    }

    public String insertBT_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_1_value, double id_2_value, double id_3_value, double id_1001_value, double id_1002_value, double id_4_value, double id_5_value, double id_6_value, double id_10_value, double id_25_value, double id_26_value, double id_27_value, double id_28_value, double id_39_value, double id_40_value, double id_56_value, double id_57_value, double id_58_value, double id_63_value, double id_70_value, double id_87_value, double id_88_value, double id_91_value, double id_92_value) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_VAL_ID_1, DBModel.COLUMN_VAL_ID_2, DBModel.COLUMN_VAL_ID_3, DBModel.COLUMN_VAL_ID_1001,
                DBModel.COLUMN_VAL_ID_1002, DBModel.COLUMN_VAL_ID_4, DBModel.COLUMN_VAL_ID_5, DBModel.COLUMN_VAL_ID_6,
                DBModel.COLUMN_VAL_ID_10, DBModel.COLUMN_VAL_ID_25, DBModel.COLUMN_VAL_ID_26, DBModel.COLUMN_VAL_ID_27,
                DBModel.COLUMN_VAL_ID_28, DBModel.COLUMN_VAL_ID_39, DBModel.COLUMN_VAL_ID_40, DBModel.COLUMN_VAL_ID_56,
                DBModel.COLUMN_VAL_ID_57, DBModel.COLUMN_VAL_ID_58, DBModel.COLUMN_VAL_ID_63, DBModel.COLUMN_VAL_ID_70,
                DBModel.COLUMN_VAL_ID_87, DBModel.COLUMN_VAL_ID_88, DBModel.COLUMN_VAL_ID_91, DBModel.COLUMN_VAL_ID_92,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_1_value, id_2_value, id_3_value, id_1001_value,
                id_1002_value, id_4_value, id_5_value, id_6_value,
                id_10_value, id_25_value, id_26_value, id_27_value,
                id_28_value, id_39_value, id_40_value, id_56_value,
                id_57_value, id_58_value, id_63_value, id_70_value,
                id_87_value, id_88_value, id_91_value, id_92_value
        );
    }

    public String insertAllValuesSQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId,
                                     double id_1_value, double id_2_value, double id_3_value, double id_4_value, double id_5_value, double id_6_value,
                                     double id_7_value, double id_8_value, double id_9_value, double id_10_value, double id_14_value, double id_15_value,
                                     double id_16_value, double id_17_value, double id_20_value, double id_21_value, double id_22_value, double id_23_value, double id_24_value, double id_25_value, double id_26_value, double id_27_value, double id_28_value, double id_29_value, double id_34_value, double id_35_value,
                                     double id_38_value, double id_39_value, double id_40_value, double id_41_value, double id_42_value, double id_43_value, double id_44_value, double id_45_value, double id_47_value, double id_50_value, double id_52_value, double id_53_value, double id_54_value, double id_55_value, double id_56_value, double id_57_value, double id_36_value,
                                     double id_60_value, double id_61_value, double id_62_value, double id_63_value, double id_64_value, double id_65_value, double id_66_value, double id_69_value, double id_70_value, double id_71_value, double id_72_value, double id_75_value, double id_76_value, double id_73_value, double id_78_value, double id_74_value, double id_88_value, double id_91_value, double id_92_value, double id_100_value, double id_101_value, double id_103_value, double id_104_value, double id_105_value, double id_106_value, double id_58_value,
                                     double id_108_value, double id_122_value, double id_123_value, double id_77_value,
                                     double id_1001_value, double id_87_value,
                                     double id_2026_value, double id_2027_value, double id_107_value,
                                     double id_2035_value, double id_2042_value, double id_2043_value, double id_2048_value, double id_2049_value, double id_4001_value, double id_4002_value, double id_4003_value, double id_4004_value, double id_4005_value, double id_2034_value, double id_1002_value, double id_4008_value, double id_4009_value, double id_4010_value, int id_1_position, int id_4_position, int id_10_position, int id_17_position, int id_37_position, int id_47_position, int id_59_position, int id_102_position, int id_1000_position, double id_4007_value, double id_4006_value, double id_125_value,
                                     int id_30_position,
                                     int id_69_position) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)" +
                        " VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_VAL_ID_1, DBModel.COLUMN_VAL_ID_2, DBModel.COLUMN_VAL_ID_3, DBModel.COLUMN_VAL_ID_4,
                DBModel.COLUMN_VAL_ID_5, DBModel.COLUMN_VAL_ID_6, DBModel.COLUMN_VAL_ID_7, DBModel.COLUMN_VAL_ID_8,
                DBModel.COLUMN_VAL_ID_9, DBModel.COLUMN_VAL_ID_10, DBModel.COLUMN_VAL_ID_14, DBModel.COLUMN_VAL_ID_15,
                DBModel.COLUMN_VAL_ID_16, DBModel.COLUMN_VAL_ID_17, DBModel.COLUMN_VAL_ID_20, DBModel.COLUMN_VAL_ID_21,
                DBModel.COLUMN_VAL_ID_22, DBModel.COLUMN_VAL_ID_23,
                DBModel.COLUMN_VAL_ID_24, DBModel.COLUMN_VAL_ID_25, DBModel.COLUMN_VAL_ID_26, DBModel.COLUMN_VAL_ID_27,
                DBModel.COLUMN_VAL_ID_28, DBModel.COLUMN_VAL_ID_29, DBModel.COLUMN_VAL_ID_34, DBModel.COLUMN_VAL_ID_35,
                DBModel.COLUMN_VAL_ID_36, DBModel.COLUMN_VAL_ID_38, DBModel.COLUMN_VAL_ID_39, DBModel.COLUMN_VAL_ID_40,
                DBModel.COLUMN_VAL_ID_41, DBModel.COLUMN_VAL_ID_42, DBModel.COLUMN_VAL_ID_43, DBModel.COLUMN_VAL_ID_44, DBModel.COLUMN_VAL_ID_45,
                DBModel.COLUMN_VAL_ID_47, DBModel.COLUMN_VAL_ID_50, DBModel.COLUMN_VAL_ID_52, DBModel.COLUMN_VAL_ID_53,
                DBModel.COLUMN_VAL_ID_54, DBModel.COLUMN_VAL_ID_55, DBModel.COLUMN_VAL_ID_56, DBModel.COLUMN_VAL_ID_57, DBModel.COLUMN_VAL_ID_58,
                DBModel.COLUMN_VAL_ID_60, DBModel.COLUMN_VAL_ID_61, DBModel.COLUMN_VAL_ID_62, DBModel.COLUMN_VAL_ID_63,
                DBModel.COLUMN_VAL_ID_64, DBModel.COLUMN_VAL_ID_65, DBModel.COLUMN_VAL_ID_66, DBModel.COLUMN_VAL_ID_69,
                DBModel.COLUMN_VAL_ID_70, DBModel.COLUMN_VAL_ID_71, DBModel.COLUMN_VAL_ID_72, DBModel.COLUMN_VAL_ID_73,
                DBModel.COLUMN_VAL_ID_74, DBModel.COLUMN_VAL_ID_75,
                DBModel.COLUMN_VAL_ID_76, DBModel.COLUMN_VAL_ID_77, DBModel.COLUMN_VAL_ID_78, DBModel.COLUMN_VAL_ID_87,
                DBModel.COLUMN_VAL_ID_88, DBModel.COLUMN_VAL_ID_91, DBModel.COLUMN_VAL_ID_92, DBModel.COLUMN_VAL_ID_100,
                DBModel.COLUMN_VAL_ID_101, DBModel.COLUMN_VAL_ID_103, DBModel.COLUMN_VAL_ID_104, DBModel.COLUMN_VAL_ID_105,
                DBModel.COLUMN_VAL_ID_106, DBModel.COLUMN_VAL_ID_107, DBModel.COLUMN_VAL_ID_108, DBModel.COLUMN_VAL_ID_122,
                DBModel.COLUMN_VAL_ID_123, DBModel.COLUMN_VAL_ID_125, DBModel.COLUMN_VAL_ID_1001, DBModel.COLUMN_VAL_ID_1002,
                DBModel.COLUMN_VAL_ID_2026, DBModel.COLUMN_VAL_ID_2027, DBModel.COLUMN_VAL_ID_2034, DBModel.COLUMN_VAL_ID_2035,
                DBModel.COLUMN_VAL_ID_2042, DBModel.COLUMN_VAL_ID_2043, DBModel.COLUMN_VAL_ID_2048, DBModel.COLUMN_VAL_ID_2049,
                DBModel.COLUMN_VAL_ID_4001, DBModel.COLUMN_VAL_ID_4002, DBModel.COLUMN_VAL_ID_4003, DBModel.COLUMN_VAL_ID_4004,
                DBModel.COLUMN_VAL_ID_4005, DBModel.COLUMN_VAL_ID_4006, DBModel.COLUMN_VAL_ID_4007, DBModel.COLUMN_VAL_ID_4008,
                DBModel.COLUMN_VAL_ID_4009, DBModel.COLUMN_VAL_ID_4010,
                DBModel.COLUMN_ID_1_POSITION, DBModel.COLUMN_ID_4_POSITION, DBModel.COLUMN_ID_10_POSITION, DBModel.COLUMN_ID_17_POSITION,
                DBModel.COLUMN_ID_30_POSITION, DBModel.COLUMN_ID_37_POSITION, DBModel.COLUMN_ID_47_POSITION, DBModel.COLUMN_ID_59_POSITION,
                DBModel.COLUMN_ID_102_POSITION, DBModel.COLUMN_ID_69_POSITION, DBModel.COLUMN_ID_1000_POSITION,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_1_value, id_2_value, id_3_value, id_4_value, id_5_value, id_6_value, id_7_value, id_8_value, id_9_value, id_10_value, id_14_value,
                id_15_value, id_16_value, id_17_value, id_20_value, id_21_value, id_22_value, id_23_value, id_24_value, id_25_value, id_26_value, id_27_value, id_28_value,
                id_29_value, id_34_value, id_35_value, id_36_value, id_38_value, id_39_value, id_40_value, id_41_value, id_42_value, id_43_value, id_44_value,
                id_45_value, id_47_value, id_50_value, id_52_value, id_53_value, id_54_value, id_55_value, id_56_value, id_57_value, id_58_value, id_60_value,
                id_61_value, id_62_value, id_63_value, id_64_value, id_65_value, id_66_value, id_69_value, id_70_value, id_71_value, id_72_value, id_73_value, id_74_value,
                id_75_value, id_76_value, id_77_value, id_78_value, id_87_value, id_88_value, id_91_value, id_92_value, id_100_value, id_101_value,
                id_103_value, id_104_value, id_105_value, id_106_value, id_107_value, id_108_value, id_122_value, id_123_value, id_125_value, id_1001_value,
                id_1002_value, id_2026_value, id_2027_value, id_2034_value, id_2035_value, id_2042_value, id_2043_value, id_2048_value, id_2049_value,
                id_4001_value, id_4002_value, id_4003_value, id_4004_value, id_4005_value, id_4006_value, id_4007_value, id_4008_value, id_4009_value,
                id_4010_value, id_1_position, id_4_position, id_10_position, id_17_position, id_30_position, id_37_position, id_47_position, id_59_position,
                id_102_position, id_69_position, id_1000_position
        );
    }

    public String insertBTThird_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, int id_1000_position, double id_1_value, double id_2_value, double id_3_value, double id_4_value, double id_5_value, double id_6_value, double id_10_value, double id_2026_value, double id_2027_value, double id_2034_value, double id_2035_value, double id_2042_value, double id_2043_value, double id_2048_value, double id_2049_value, double id_39_value, double id_40_value) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_ID_1000_POSITION, DBModel.COLUMN_VAL_ID_1, DBModel.COLUMN_VAL_ID_2, DBModel.COLUMN_VAL_ID_3, DBModel.COLUMN_VAL_ID_4,
                DBModel.COLUMN_VAL_ID_5, DBModel.COLUMN_VAL_ID_6, DBModel.COLUMN_VAL_ID_10,
                DBModel.COLUMN_VAL_ID_2026, DBModel.COLUMN_VAL_ID_2027,
                DBModel.COLUMN_VAL_ID_2034, DBModel.COLUMN_VAL_ID_2035,
                DBModel.COLUMN_VAL_ID_2042, DBModel.COLUMN_VAL_ID_2043,
                DBModel.COLUMN_VAL_ID_2048, DBModel.COLUMN_VAL_ID_2049,
                DBModel.COLUMN_VAL_ID_39, DBModel.COLUMN_VAL_ID_40,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_1000_position, id_1_value, id_2_value, id_3_value, id_4_value,
                id_5_value, id_6_value, id_10_value,
                id_2026_value, id_2027_value, id_2034_value, id_2035_value,
                id_2042_value, id_2043_value, id_2048_value, id_2049_value,
                id_39_value, id_40_value
        );
    }

    public String insertCL_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_101_value, int id_1_position, double id_2_value, double id_3_value, int id_4_position, int id_102_position, double id_5_value, double id_125_value, double id_6_value, double id_7_value, double id_8_value, double id_104_value, double id_15_value) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, DBModel.COLUMN_VAL_ID_101, DBModel.COLUMN_ID_1_POSITION,
                DBModel.COLUMN_VAL_ID_2, DBModel.COLUMN_VAL_ID_3, DBModel.COLUMN_ID_4_POSITION,
                DBModel.COLUMN_ID_102_POSITION, DBModel.COLUMN_VAL_ID_5, DBModel.COLUMN_VAL_ID_125,
                DBModel.COLUMN_VAL_ID_6, DBModel.COLUMN_VAL_ID_7, DBModel.COLUMN_VAL_ID_8,
                DBModel.COLUMN_VAL_ID_104, DBModel.COLUMN_VAL_ID_15,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_101_value, id_1_position, id_2_value, id_3_value, id_4_position,
                id_102_position, id_5_value, id_125_value, id_6_value,
                id_7_value, id_8_value, id_104_value, id_15_value);
    }

    public String insertCLFourth_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_122_value, double id_123_value) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID,
                DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_VAL_ID_122, DBModel.COLUMN_VAL_ID_123,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_122_value, id_123_value);
    }

    public String insertPenetration_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_1_value, double id_2_value, double id_3_value, double id_108_value, double id_9_value, double id_10_value, double id_15_value, double id_16_value, double id_100_value, double id_101_value, double id_103_value, double id_104_value, double id_105_value, double id_106_value, double id_107_value, double id_22_value, double id_23_value, double id_24_value, double id_25_value, double id_36_value, double id_38_value, double id_41_value, double id_43_value, double id_45_value, double id_62_value, double id_63_value, double id_66_value, int id_69_position, double id_4001_value, double id_4002_value, double id_4003_value, double id_4004_value, double id_4005_value, double id_4006_value, double id_4007_value, double id_4008_value, double id_4009_value, double id_4010_value) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_VAL_ID_1, DBModel.COLUMN_VAL_ID_2, DBModel.COLUMN_VAL_ID_3, DBModel.COLUMN_VAL_ID_108,
                DBModel.COLUMN_VAL_ID_9, DBModel.COLUMN_VAL_ID_10, DBModel.COLUMN_VAL_ID_15, DBModel.COLUMN_VAL_ID_16,
                DBModel.COLUMN_VAL_ID_100, DBModel.COLUMN_VAL_ID_101, DBModel.COLUMN_VAL_ID_103, DBModel.COLUMN_VAL_ID_104,
                DBModel.COLUMN_VAL_ID_105, DBModel.COLUMN_VAL_ID_106, DBModel.COLUMN_VAL_ID_107,
                DBModel.COLUMN_VAL_ID_22, DBModel.COLUMN_VAL_ID_23, DBModel.COLUMN_VAL_ID_24, DBModel.COLUMN_VAL_ID_25,
                DBModel.COLUMN_VAL_ID_36, DBModel.COLUMN_VAL_ID_38, DBModel.COLUMN_VAL_ID_41, DBModel.COLUMN_VAL_ID_43,
                DBModel.COLUMN_VAL_ID_45, DBModel.COLUMN_VAL_ID_62, DBModel.COLUMN_VAL_ID_63, DBModel.COLUMN_VAL_ID_66,
                DBModel.COLUMN_ID_69_POSITION, DBModel.COLUMN_VAL_ID_4001, DBModel.COLUMN_VAL_ID_4002, DBModel.COLUMN_VAL_ID_4003,
                DBModel.COLUMN_VAL_ID_4004, DBModel.COLUMN_VAL_ID_4005, DBModel.COLUMN_VAL_ID_4006, DBModel.COLUMN_VAL_ID_4007,
                DBModel.COLUMN_VAL_ID_4008, DBModel.COLUMN_VAL_ID_4009, DBModel.COLUMN_VAL_ID_4010,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_1_value, id_2_value, id_3_value, id_108_value,
                id_9_value, id_10_value, id_15_value, id_16_value,
                id_100_value, id_101_value, id_103_value, id_104_value, id_105_value, id_106_value, id_107_value,
                id_22_value, id_23_value, id_24_value, id_25_value,
                id_36_value, id_38_value, id_41_value, id_43_value,
                id_45_value, id_62_value, id_63_value, id_66_value,
                id_69_position, id_4001_value, id_4002_value, id_4003_value,
                id_4004_value, id_4005_value, id_4006_value, id_4007_value,
                id_4008_value, id_4009_value, id_4010_value);
    }

    public String updateCL_SQL(double id_101_value, int id_1_position, double id_2_value, double id_3_value, int id_4_position, int id_102_position, double id_5_value, double id_125_value, double id_6_value, double id_7_value, double id_8_value, double id_104_value, double id_15_value, String savedVersionTitle, int moduleActiveId, int categoryActiveId, int subCategoryActiveId) {
        return String.format("UPDATE %s SET %s='%s', %s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_VAL_ID_101, id_101_value,
                DBModel.COLUMN_ID_1_POSITION, id_1_position,
                DBModel.COLUMN_VAL_ID_2, id_2_value,
                DBModel.COLUMN_VAL_ID_3, id_3_value,
                DBModel.COLUMN_ID_4_POSITION, id_4_position,
                DBModel.COLUMN_ID_102_POSITION, id_102_position,
                DBModel.COLUMN_VAL_ID_5, id_5_value,
                DBModel.COLUMN_VAL_ID_125, id_125_value,
                DBModel.COLUMN_VAL_ID_6, id_6_value,
                DBModel.COLUMN_VAL_ID_7, id_7_value,
                DBModel.COLUMN_VAL_ID_8, id_8_value,
                DBModel.COLUMN_VAL_ID_104, id_104_value,
                DBModel.COLUMN_VAL_ID_15, id_15_value,
                DBModel.COLUMN_TITLE, savedVersionTitle,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal
        );
    }

    public String updateCLFourth_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_122_value, double id_123_value) {
        return String.format("UPDATE %s SET %s='%s', %s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_VAL_ID_122, id_122_value,
                DBModel.COLUMN_VAL_ID_123, id_123_value,
                DBModel.COLUMN_TITLE, title,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal
        );
    }

    public String updateCL_SQL(double id_1_value, double id_2_value, double id_3_value, double id_108_value, double id_9_value, double id_10_value, double id_15_value, double id_16_value, double id_100_value, double id_101_value, double id_103_value, double id_104_value, double id_105_value, double id_106_value, double id_107_value, double id_22_value, double id_23_value, double id_24_value, double id_25_value, double id_36_value, double id_38_value, double id_41_value, double id_43_value, double id_45_value, double id_62_value, double id_63_value, double id_66_value, int id_69_position, double id_4001_value, double id_4002_value, double id_4003_value, double id_4004_value, double id_4005_value, double id_4006_value, double id_4007_value, double id_4008_value, double id_4009_value, double id_4010_value, String savedVersionTitle, int moduleActiveId, int categoryActiveId, int subCategoryActiveId) {
        return String.format("UPDATE %s SET %s='%s', %s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_VAL_ID_1, id_1_value,
                DBModel.COLUMN_VAL_ID_2, id_2_value,
                DBModel.COLUMN_VAL_ID_3, id_3_value,
                DBModel.COLUMN_VAL_ID_108, id_108_value,
                DBModel.COLUMN_VAL_ID_9, id_9_value,
                DBModel.COLUMN_VAL_ID_10, id_10_value,
                DBModel.COLUMN_VAL_ID_15, id_15_value,
                DBModel.COLUMN_VAL_ID_16, id_16_value,
                DBModel.COLUMN_VAL_ID_100, id_100_value,
                DBModel.COLUMN_VAL_ID_101, id_101_value,
                DBModel.COLUMN_VAL_ID_103, id_103_value,
                DBModel.COLUMN_VAL_ID_104, id_104_value,
                DBModel.COLUMN_VAL_ID_105, id_105_value,
                DBModel.COLUMN_VAL_ID_106, id_106_value,
                DBModel.COLUMN_VAL_ID_107, id_107_value,
                DBModel.COLUMN_VAL_ID_22, id_22_value,
                DBModel.COLUMN_VAL_ID_23, id_23_value,
                DBModel.COLUMN_VAL_ID_24, id_24_value,
                DBModel.COLUMN_VAL_ID_25, id_25_value,
                DBModel.COLUMN_VAL_ID_36, id_36_value,
                DBModel.COLUMN_VAL_ID_38, id_38_value,
                DBModel.COLUMN_VAL_ID_41, id_41_value,
                DBModel.COLUMN_VAL_ID_43, id_43_value,
                DBModel.COLUMN_VAL_ID_45, id_45_value,
                DBModel.COLUMN_VAL_ID_62, id_62_value,
                DBModel.COLUMN_VAL_ID_63, id_63_value,
                DBModel.COLUMN_VAL_ID_66, id_66_value,
                DBModel.COLUMN_ID_69_POSITION, id_69_position,
                DBModel.COLUMN_VAL_ID_4001, id_4001_value,
                DBModel.COLUMN_VAL_ID_4002, id_4002_value,
                DBModel.COLUMN_VAL_ID_4003, id_4003_value,
                DBModel.COLUMN_VAL_ID_4004, id_4004_value,
                DBModel.COLUMN_VAL_ID_4005, id_4005_value,
                DBModel.COLUMN_VAL_ID_4006, id_4006_value,
                DBModel.COLUMN_VAL_ID_4007, id_4007_value,
                DBModel.COLUMN_VAL_ID_4008, id_4008_value,
                DBModel.COLUMN_VAL_ID_4009, id_4009_value,
                DBModel.COLUMN_VAL_ID_4010, id_4010_value,
                DBModel.COLUMN_TITLE, savedVersionTitle,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal
        );
    }

    public String insertPagingCategoryOne_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, int id_1_position, double id_2_value,
                                              double id_3_value, double id_4_value, double id_7_value, double id_8_value, double id_9_value, int id_10_position,
                                              double id_14_value, double id_15_value, double id_16_value, int id_17_position, double id_20_value, double id_22_value,
                                              double id_23_value, double id_27_value, double id_28_value, double id_29_value, int id_30_position, double id_34_value,
                                              double id_35_value, double id_36_value, int id_37_position, double id_40_value, double id_41_value, double id_42_value,
                                              double id_45_value, double id_47_value, double id_50_value, double id_52_value, double id_53_value, double id_54_value,
                                              double id_58_value, double id_60_value, double id_61_value, double id_62_value, double id_64_value, double id_65_value,
                                              double id_66_value, double id_69_value, double id_70_value, double id_73_value, double id_74_value, double id_75_value,
                                              double id_76_value, double id_77_value, double id_78_value) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_ID_1_POSITION, DBModel.COLUMN_VAL_ID_2, DBModel.COLUMN_VAL_ID_3, DBModel.COLUMN_VAL_ID_4,
                DBModel.COLUMN_VAL_ID_7, DBModel.COLUMN_VAL_ID_8, DBModel.COLUMN_VAL_ID_9, DBModel.COLUMN_ID_10_POSITION,
                DBModel.COLUMN_VAL_ID_14, DBModel.COLUMN_VAL_ID_15, DBModel.COLUMN_VAL_ID_16, DBModel.COLUMN_ID_17_POSITION,
                DBModel.COLUMN_VAL_ID_20, DBModel.COLUMN_VAL_ID_22, DBModel.COLUMN_VAL_ID_23,
                DBModel.COLUMN_VAL_ID_27, DBModel.COLUMN_VAL_ID_28, DBModel.COLUMN_VAL_ID_29, DBModel.COLUMN_ID_30_POSITION,
                DBModel.COLUMN_VAL_ID_34, DBModel.COLUMN_VAL_ID_35, DBModel.COLUMN_VAL_ID_36, DBModel.COLUMN_ID_37_POSITION,
                DBModel.COLUMN_VAL_ID_40, DBModel.COLUMN_VAL_ID_41, DBModel.COLUMN_VAL_ID_42, DBModel.COLUMN_VAL_ID_45,
                DBModel.COLUMN_VAL_ID_47, DBModel.COLUMN_VAL_ID_50, DBModel.COLUMN_VAL_ID_52, DBModel.COLUMN_VAL_ID_53,
                DBModel.COLUMN_VAL_ID_54, DBModel.COLUMN_VAL_ID_58, DBModel.COLUMN_VAL_ID_60, DBModel.COLUMN_VAL_ID_61,
                DBModel.COLUMN_VAL_ID_62, DBModel.COLUMN_VAL_ID_64, DBModel.COLUMN_VAL_ID_65, DBModel.COLUMN_VAL_ID_66,
                DBModel.COLUMN_VAL_ID_69, DBModel.COLUMN_VAL_ID_70, DBModel.COLUMN_VAL_ID_73, DBModel.COLUMN_VAL_ID_74,
                DBModel.COLUMN_VAL_ID_75, DBModel.COLUMN_VAL_ID_76, DBModel.COLUMN_VAL_ID_77, DBModel.COLUMN_VAL_ID_78,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_1_position, id_2_value, id_3_value, id_4_value, id_7_value, id_8_value, id_9_value, id_10_position,
                id_14_value, id_15_value, id_16_value, id_17_position, id_20_value, id_22_value, id_23_value,
                id_27_value, id_28_value, id_29_value, id_30_position, id_34_value, id_35_value, id_36_value, id_37_position,
                id_40_value, id_41_value, id_42_value, id_45_value, id_47_value, id_50_value, id_52_value, id_53_value,
                id_54_value, id_58_value, id_60_value, id_61_value, id_62_value, id_64_value, id_65_value,
                id_66_value, id_69_value, id_70_value, id_73_value, id_74_value, id_75_value, id_76_value, id_77_value, id_78_value);
    }

    public String updatePaging_SQL(String savedVersionTitle, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, int id_1_position, double id_2_value, double id_3_value,
                                   double id_4_value, double id_7_value, double id_8_value, double id_9_value, int id_10_position, double id_14_value,
                                   double id_15_value, double id_16_value, int id_17_position, double id_20_value, double id_22_value, double id_23_value,
                                   double id_27_value, double id_28_value, double id_29_value, int id_30_position, double id_34_value, double id_35_value,
                                   double id_36_value, int id_37_position, double id_40_value, double id_41_value, double id_42_value, double id_45_value,
                                   double id_47_value, double id_50_value, double id_52_value, double id_53_value, double id_54_value, double id_58_value,
                                   double id_60_value, double id_61_value, double id_62_value, double id_64_value, double id_65_value, double id_66_value,
                                   double id_69_value, double id_70_value, double id_73_value, double id_74_value, double id_75_value, double id_76_value,
                                   double id_77_value, double id_78_value) {
        return String.format("UPDATE %s SET %s='%s', %s='%s',%s='%s',%s='%s', %s='%s',%s='%s',%s='%s', %s='%s',%s='%s',%s='%s', %s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_TITLE, savedVersionTitle,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal,
                DBModel.COLUMN_ID_1_POSITION, id_1_position,
                DBModel.COLUMN_VAL_ID_2, id_2_value,
                DBModel.COLUMN_VAL_ID_3, id_3_value,
                DBModel.COLUMN_VAL_ID_4, id_4_value,
                DBModel.COLUMN_VAL_ID_7, id_7_value,
                DBModel.COLUMN_VAL_ID_8, id_8_value,
                DBModel.COLUMN_VAL_ID_9, id_9_value,
                DBModel.COLUMN_ID_10_POSITION, id_10_position,
                DBModel.COLUMN_VAL_ID_14, id_14_value,
                DBModel.COLUMN_VAL_ID_15, id_15_value,
                DBModel.COLUMN_VAL_ID_16, id_16_value,
                DBModel.COLUMN_ID_17_POSITION, id_17_position,
                DBModel.COLUMN_VAL_ID_20, id_20_value,
                DBModel.COLUMN_VAL_ID_22, id_22_value,
                DBModel.COLUMN_VAL_ID_23, id_23_value,
                DBModel.COLUMN_VAL_ID_27, id_27_value,
                DBModel.COLUMN_VAL_ID_28, id_28_value,
                DBModel.COLUMN_VAL_ID_29, id_29_value,
                DBModel.COLUMN_ID_30_POSITION, id_30_position,
                DBModel.COLUMN_VAL_ID_34, id_34_value,
                DBModel.COLUMN_VAL_ID_35, id_35_value,
                DBModel.COLUMN_VAL_ID_36, id_36_value,
                DBModel.COLUMN_ID_37_POSITION, id_37_position,
                DBModel.COLUMN_VAL_ID_40, id_40_value,
                DBModel.COLUMN_VAL_ID_41, id_41_value,
                DBModel.COLUMN_VAL_ID_42, id_42_value,
                DBModel.COLUMN_VAL_ID_45, id_45_value,
                DBModel.COLUMN_VAL_ID_47, id_47_value,
                DBModel.COLUMN_VAL_ID_50, id_50_value,
                DBModel.COLUMN_VAL_ID_52, id_52_value,
                DBModel.COLUMN_VAL_ID_53, id_53_value,
                DBModel.COLUMN_VAL_ID_54, id_54_value,
                DBModel.COLUMN_VAL_ID_58, id_58_value,
                DBModel.COLUMN_VAL_ID_60, id_60_value,
                DBModel.COLUMN_VAL_ID_61, id_61_value,
                DBModel.COLUMN_VAL_ID_62, id_62_value,
                DBModel.COLUMN_VAL_ID_64, id_64_value,
                DBModel.COLUMN_VAL_ID_65, id_65_value,
                DBModel.COLUMN_VAL_ID_66, id_66_value,
                DBModel.COLUMN_VAL_ID_69, id_69_value,
                DBModel.COLUMN_VAL_ID_70, id_70_value,
                DBModel.COLUMN_VAL_ID_73, id_73_value,
                DBModel.COLUMN_VAL_ID_74, id_74_value,
                DBModel.COLUMN_VAL_ID_75, id_75_value,
                DBModel.COLUMN_VAL_ID_76, id_76_value,
                DBModel.COLUMN_VAL_ID_77, id_77_value,
                DBModel.COLUMN_VAL_ID_78, id_78_value
        );
    }

    public String insertPagingCategoryTwo_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_1_value, double id_2_value,
                                              double id_3_value, double id_4_value, double id_400_value, double id_6_value, double id_9_value, double id_21_value,
                                              double id_22_value, double id_27_value, double id_34_value, double id_35_value, int id_42_position, double id_43_value,
                                              double id_44_value, double id_45_value, double id_48_value, double id_49_value, double id_50_value, int id_51_position,
                                              double id_55_value, double id_56_value, double id_57_value, int id_58_position, double id_61_value, double id_62_value,
                                              double id_63_value, double id_67_value, double id_68_value, double id_69_value, int id_70_position, double id_74_value,
                                              double id_75_value, double id_76_value, int id_77_position, double id_80_value, double id_81_value, double id_82_value,
                                              int id_85_position, int id_86_position, double id_88_value, double id_89_value, double id_90_value, int id_94_position,
                                              double id_96_value, double id_97_value, double id_115_value, double id_116_value, double id_270_value) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_VAL_ID_1, DBModel.COLUMN_VAL_ID_2, DBModel.COLUMN_VAL_ID_3, DBModel.COLUMN_VAL_ID_4,
                DBModel.COLUMN_VAL_ID_400, DBModel.COLUMN_VAL_ID_6, DBModel.COLUMN_VAL_ID_9, DBModel.COLUMN_VAL_ID_21,
                DBModel.COLUMN_VAL_ID_22, DBModel.COLUMN_VAL_ID_27, DBModel.COLUMN_VAL_ID_34, DBModel.COLUMN_VAL_ID_35,
                DBModel.COLUMN_ID_42_POSITION, DBModel.COLUMN_VAL_ID_43, DBModel.COLUMN_VAL_ID_44, DBModel.COLUMN_VAL_ID_45,
                DBModel.COLUMN_VAL_ID_48, DBModel.COLUMN_VAL_ID_49, DBModel.COLUMN_VAL_ID_50, DBModel.COLUMN_ID_51_POSITION,
                DBModel.COLUMN_VAL_ID_55, DBModel.COLUMN_VAL_ID_56, DBModel.COLUMN_VAL_ID_57, DBModel.COLUMN_ID_58_POSITION,
                DBModel.COLUMN_VAL_ID_61, DBModel.COLUMN_VAL_ID_62, DBModel.COLUMN_VAL_ID_63, DBModel.COLUMN_VAL_ID_67,
                DBModel.COLUMN_VAL_ID_68, DBModel.COLUMN_VAL_ID_69, DBModel.COLUMN_ID_70_POSITION, DBModel.COLUMN_VAL_ID_74,
                DBModel.COLUMN_VAL_ID_75, DBModel.COLUMN_VAL_ID_76, DBModel.COLUMN_ID_77_POSITION, DBModel.COLUMN_VAL_ID_80,
                DBModel.COLUMN_VAL_ID_81, DBModel.COLUMN_VAL_ID_82, DBModel.COLUMN_ID_85_POSITION, DBModel.COLUMN_ID_86_POSITION,
                DBModel.COLUMN_VAL_ID_88, DBModel.COLUMN_VAL_ID_89, DBModel.COLUMN_VAL_ID_90, DBModel.COLUMN_ID_94_POSITION,
                DBModel.COLUMN_VAL_ID_96, DBModel.COLUMN_VAL_ID_97, DBModel.COLUMN_VAL_ID_115, DBModel.COLUMN_VAL_ID_116,
                DBModel.COLUMN_VAL_ID_270,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_1_value, id_2_value, id_3_value, id_4_value, id_400_value, id_6_value, id_9_value, id_21_value,
                id_22_value, id_27_value, id_34_value, id_35_value, id_42_position, id_43_value, id_44_value,
                id_45_value, id_48_value, id_49_value, id_50_value, id_51_position, id_55_value, id_56_value, id_57_value,
                id_58_position, id_61_value, id_62_value, id_63_value, id_67_value, id_68_value, id_69_value, id_70_position,
                id_74_value, id_75_value, id_76_value, id_77_position, id_80_value, id_81_value, id_82_value,
                id_85_position, id_86_position, id_88_value, id_89_value, id_90_value, id_94_position, id_96_value, id_97_value,
                id_115_value, id_116_value, id_270_value);
    }

    public String updatePagingCategoryTwo_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_1_value, double id_2_value, double id_3_value, double id_4_value, double id_400_value, double id_6_value, double id_9_value, double id_21_value, double id_22_value, double id_27_value, double id_34_value, double id_35_value, int id_42_position, double id_43_value, double id_44_value, double id_45_value, double id_48_value, double id_49_value, double id_50_value, int id_51_position, double id_55_value, double id_56_value, double id_57_value, int id_58_position, double id_61_value, double id_62_value, double id_63_value, double id_67_value, double id_68_value, double id_69_value, int id_70_position, double id_74_value, double id_75_value, double id_76_value, int id_77_position, double id_80_value, double id_81_value, double id_82_value, int id_85_position, int id_86_position, double id_88_value, double id_89_value, double id_90_value, int id_94_position, double id_96_value, double id_97_value, double id_115_value, double id_116_value, double id_270_value) {
        return String.format("UPDATE %s SET %s='%s',%s='%s',%s='%s', %s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_VAL_ID_1, id_1_value,
                DBModel.COLUMN_VAL_ID_2, id_2_value,
                DBModel.COLUMN_VAL_ID_3, id_3_value,
                DBModel.COLUMN_VAL_ID_4, id_4_value,
                DBModel.COLUMN_VAL_ID_400, id_400_value,
                DBModel.COLUMN_VAL_ID_6, id_6_value,
                DBModel.COLUMN_VAL_ID_9, id_9_value,
                DBModel.COLUMN_VAL_ID_21, id_21_value,
                DBModel.COLUMN_VAL_ID_22, id_22_value,
                DBModel.COLUMN_VAL_ID_27, id_27_value,
                DBModel.COLUMN_VAL_ID_34, id_34_value,
                DBModel.COLUMN_VAL_ID_35, id_35_value,
                DBModel.COLUMN_ID_42_POSITION, id_42_position,
                DBModel.COLUMN_VAL_ID_43, id_43_value,
                DBModel.COLUMN_VAL_ID_44, id_44_value,
                DBModel.COLUMN_VAL_ID_45, id_45_value,
                DBModel.COLUMN_VAL_ID_48, id_48_value,
                DBModel.COLUMN_VAL_ID_49, id_49_value,
                DBModel.COLUMN_VAL_ID_50, id_50_value,
                DBModel.COLUMN_ID_51_POSITION, id_51_position,
                DBModel.COLUMN_VAL_ID_55, id_55_value,
                DBModel.COLUMN_VAL_ID_56, id_56_value,
                DBModel.COLUMN_VAL_ID_57, id_57_value,
                DBModel.COLUMN_ID_58_POSITION, id_58_position,
                DBModel.COLUMN_VAL_ID_61, id_61_value,
                DBModel.COLUMN_VAL_ID_62, id_62_value,
                DBModel.COLUMN_VAL_ID_63, id_63_value,
                DBModel.COLUMN_VAL_ID_67, id_67_value,
                DBModel.COLUMN_VAL_ID_68, id_68_value,
                DBModel.COLUMN_VAL_ID_69, id_69_value,
                DBModel.COLUMN_ID_70_POSITION, id_70_position,
                DBModel.COLUMN_VAL_ID_74, id_74_value,
                DBModel.COLUMN_VAL_ID_75, id_75_value,
                DBModel.COLUMN_VAL_ID_76, id_76_value,
                DBModel.COLUMN_ID_77_POSITION, id_77_position,
                DBModel.COLUMN_VAL_ID_80, id_80_value,
                DBModel.COLUMN_VAL_ID_81, id_81_value,
                DBModel.COLUMN_VAL_ID_82, id_82_value,
                DBModel.COLUMN_ID_85_POSITION, id_85_position,
                DBModel.COLUMN_ID_86_POSITION, id_86_position,
                DBModel.COLUMN_VAL_ID_88, id_88_value,
                DBModel.COLUMN_VAL_ID_89, id_89_value,
                DBModel.COLUMN_VAL_ID_90, id_90_value,
                DBModel.COLUMN_ID_94_POSITION, id_94_position,
                DBModel.COLUMN_VAL_ID_96, id_96_value,
                DBModel.COLUMN_VAL_ID_97, id_97_value,
                DBModel.COLUMN_VAL_ID_115, id_115_value,
                DBModel.COLUMN_VAL_ID_116, id_116_value,
                DBModel.COLUMN_VAL_ID_270, id_270_value,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal,
                DBModel.COLUMN_TITLE, title,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId);
    }

    public String insertSteelCeiling_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_1_value, double id_14_value, double id_15_value, double id_17_value, double id_21_value, double id_22_value, double id_23_value, double id_27_value, double id_43_value, double id_44_value, double id_55_value, double id_56_value, double id_66_value, double id_71_value, double id_72_value, int id_47_position, int id_59_position) {
        return String.format("INSERT INTO %s (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) VALUES ('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')", DBModel.VALUES_TABLE,
                DBModel.COLUMN_EMAIL, DBModel.COLUMN_TITLE, DBModel.COLUMN_MODULE_ID, DBModel.COLUMN_CATEGORY_ID, DBModel.COLUMN_SUB_CATEGORY_POSITION,
                DBModel.COLUMN_VAL_ID_1, DBModel.COLUMN_VAL_ID_14, DBModel.COLUMN_VAL_ID_15, DBModel.COLUMN_VAL_ID_17,
                DBModel.COLUMN_VAL_ID_21, DBModel.COLUMN_VAL_ID_22, DBModel.COLUMN_VAL_ID_23, DBModel.COLUMN_VAL_ID_27,
                DBModel.COLUMN_VAL_ID_43, DBModel.COLUMN_VAL_ID_44, DBModel.COLUMN_VAL_ID_55, DBModel.COLUMN_VAL_ID_56,
                DBModel.COLUMN_VAL_ID_66, DBModel.COLUMN_VAL_ID_71, DBModel.COLUMN_VAL_ID_72,
                DBModel.COLUMN_ID_47_POSITION, DBModel.COLUMN_ID_59_POSITION,
                currentUserEmailGlobal, title, moduleActiveId, categoryActiveId, subCategoryActiveId,
                id_1_value, id_14_value, id_15_value, id_17_value, id_21_value, id_22_value, id_23_value, id_27_value, id_43_value,
                id_44_value, id_55_value, id_56_value, id_66_value, id_71_value, id_72_value, id_47_position, id_59_position);
    }

    public String updateSteelCeiling_SQL(String title, int moduleActiveId, int categoryActiveId, int subCategoryActiveId, double id_1_value, double id_14_value,
                                         double id_15_value, double id_17_value, double id_21_value, double id_22_value, double id_23_value, double id_27_value,
                                         double id_43_value, double id_44_value, double id_55_value, double id_56_value, double id_66_value, double id_71_value,
                                         double id_72_value, int id_47_position, int id_59_position) {
        return String.format("UPDATE %s SET %s='%s',%s='%s',%s='%s', %s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s',%s='%s' WHERE %s='%s' AND %s='%s' AND %s='%s' AND %s='%s' AND %s='%s'", DBModel.VALUES_TABLE,
                DBModel.COLUMN_VAL_ID_1, id_1_value,
                DBModel.COLUMN_VAL_ID_14, id_14_value,
                DBModel.COLUMN_VAL_ID_15, id_15_value,
                DBModel.COLUMN_VAL_ID_17, id_17_value,
                DBModel.COLUMN_VAL_ID_21, id_21_value,
                DBModel.COLUMN_VAL_ID_22, id_22_value,
                DBModel.COLUMN_VAL_ID_23, id_23_value,
                DBModel.COLUMN_VAL_ID_27, id_27_value,
                DBModel.COLUMN_VAL_ID_43, id_43_value,
                DBModel.COLUMN_VAL_ID_44, id_44_value,
                DBModel.COLUMN_VAL_ID_55, id_55_value,
                DBModel.COLUMN_VAL_ID_56, id_56_value,
                DBModel.COLUMN_VAL_ID_66, id_66_value,
                DBModel.COLUMN_VAL_ID_71, id_71_value,
                DBModel.COLUMN_VAL_ID_72, id_72_value,
                DBModel.COLUMN_ID_47_POSITION, id_47_position,
                DBModel.COLUMN_ID_59_POSITION, id_59_position,
                DBModel.COLUMN_EMAIL, currentUserEmailGlobal,
                DBModel.COLUMN_TITLE, title,
                DBModel.COLUMN_MODULE_ID, moduleActiveId,
                DBModel.COLUMN_CATEGORY_ID, categoryActiveId,
                DBModel.COLUMN_SUB_CATEGORY_POSITION, subCategoryActiveId);

    }

}
